#### 6.1 Loading the Evaluation Results

The model evaluation results generated in the previous notebook were loaded for comparative analysis.

The comparison uses MAE, RMSE, and R² to examine differences in predictive performance across individual, tuned, and ensemble models.

In [1]:
# Importing the required libraries

import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
# Loading the evaluation results

evaluation_results = pd.DataFrame([
    ['lasso_regression', 52.605610, 67.587760, 0.874712],
    ['linear_regression', 52.613793, 67.588549, 0.874709],
    ['ridge_regression', 52.594296, 67.589301, 0.874706],
    ['stacking_regression', 52.064850, 67.782372, 0.873989],
    ['voting_regression', 52.910708, 69.630254, 0.867025],
    ['mlp_regressor', 55.528218, 69.890885, 0.866028],
    ['gradient_boosting_tuned', 53.341282, 69.921527, 0.865910],
    ['xgboost', 54.229044, 71.930902, 0.858093],
    ['extra_trees', 53.020429, 72.036286, 0.857677],
    ['gradient_boosting', 53.676876, 72.121650, 0.857339],
    ['lightgbm_tuned', 54.766373, 72.193410, 0.857055],
    ['xgboost_tuned', 54.734186, 73.511676, 0.851787],
    ['random_forest', 55.613818, 74.643601, 0.847187],
    ['random_forest_tuned', 63.356502, 78.912524, 0.829209],
    ['lightgbm', 57.970616, 79.134624, 0.828246],
    ['extra_trees_tuned', 66.926870, 83.894603, 0.806962]
], columns=['Model', 'MAE', 'RMSE', 'R²'])

In [3]:
# Checking the evaluation results

evaluation_results

                      Model        MAE       RMSE        R²
0          lasso_regression  52.605610  67.587760  0.874712
1         linear_regression  52.613793  67.588549  0.874709
2          ridge_regression  52.594296  67.589301  0.874706
3       stacking_regression  52.064850  67.782372  0.873989
4         voting_regression  52.910708  69.630254  0.867025
5             mlp_regressor  55.528218  69.890885  0.866028
6   gradient_boosting_tuned  53.341282  69.921527  0.865910
7                   xgboost  54.229044  71.930902  0.858093
8               extra_trees  53.020429  72.036286  0.857677
9         gradient_boosting  53.676876  72.121650  0.857339
10           lightgbm_tuned  54.766373  72.193410  0.857055
11            xgboost_tuned  54.734186  73.511676  0.851787
12            random_forest  55.613818  74.643601  0.847187
13      random_forest_tuned  63.356502  78.912524  0.829209
14                 lightgbm  57.970616  79.134624  0.828246
15        extra_trees_tuned  66.926870  83.894603  0.806962

#### Observation on Model Evaluation Results

The evaluation dataset contains results for all 16 trained models across three complementary regression metrics: MAE, RMSE, and R². The results provide a consistent basis for comparing linear, non-linear, tuned, and ensemble approaches.

#### Important Point

The evaluation results are based on predictions generated from the held-out test dataset. Therefore, the comparison reflects model performance on previously unseen observations rather than training performance.

#### 6.2 Metric-Based Model Comparison

The trained models were compared across Mean Absolute Error (MAE), Root Mean Squared Error (RMSE), and R².

MAE and RMSE measure prediction error, where lower values indicate better performance. R² measures the proportion of variation in historical ride costs explained by the model, where higher values indicate stronger explanatory performance.

Each metric was examined separately to identify differences in model behavior across the evaluation criteria.

In [4]:
# Comparing models by MAE

mae_comparison = evaluation_results.sort_values(
    by='MAE',
    ascending=True
).reset_index(drop=True)

mae_comparison

                      Model        MAE       RMSE        R²
0       stacking_regression  52.064850  67.782372  0.873989
1          ridge_regression  52.594296  67.589301  0.874706
2          lasso_regression  52.605610  67.587760  0.874712
3         linear_regression  52.613793  67.588549  0.874709
4         voting_regression  52.910708  69.630254  0.867025
5               extra_trees  53.020429  72.036286  0.857677
6   gradient_boosting_tuned  53.341282  69.921527  0.865910
7         gradient_boosting  53.676876  72.121650  0.857339
8                   xgboost  54.229044  71.930902  0.858093
9             xgboost_tuned  54.734186  73.511676  0.851787
10           lightgbm_tuned  54.766373  72.193410  0.857055
11            mlp_regressor  55.528218  69.890885  0.866028
12            random_forest  55.613818  74.643601  0.847187
13                 lightgbm  57.970616  79.134624  0.828246
14      random_forest_tuned  63.356502  78.912524  0.829209
15        extra_trees_tuned  66.926870  83.894603  0.806962

In [5]:
# Comparing models by RMSE

rmse_comparison = evaluation_results.sort_values(
    by='RMSE',
    ascending=True
).reset_index(drop=True)

rmse_comparison

                      Model        MAE       RMSE        R²
0          lasso_regression  52.605610  67.587760  0.874712
1         linear_regression  52.613793  67.588549  0.874709
2          ridge_regression  52.594296  67.589301  0.874706
3       stacking_regression  52.064850  67.782372  0.873989
4         voting_regression  52.910708  69.630254  0.867025
5             mlp_regressor  55.528218  69.890885  0.866028
6   gradient_boosting_tuned  53.341282  69.921527  0.865910
7                   xgboost  54.229044  71.930902  0.858093
8               extra_trees  53.020429  72.036286  0.857677
9         gradient_boosting  53.676876  72.121650  0.857339
10           lightgbm_tuned  54.766373  72.193410  0.857055
11            xgboost_tuned  54.734186  73.511676  0.851787
12            random_forest  55.613818  74.643601  0.847187
13      random_forest_tuned  63.356502  78.912524  0.829209
14                 lightgbm  57.970616  79.134624  0.828246
15        extra_trees_tuned  66.926870  83.894603  0.806962

In [6]:
# Comparing models by R²

r2_comparison = evaluation_results.sort_values(
    by='R²',
    ascending=False
).reset_index(drop=True)

r2_comparison

                      Model        MAE       RMSE        R²
0          lasso_regression  52.605610  67.587760  0.874712
1         linear_regression  52.613793  67.588549  0.874709
2          ridge_regression  52.594296  67.589301  0.874706
3       stacking_regression  52.064850  67.782372  0.873989
4         voting_regression  52.910708  69.630254  0.867025
5             mlp_regressor  55.528218  69.890885  0.866028
6   gradient_boosting_tuned  53.341282  69.921527  0.865910
7                   xgboost  54.229044  71.930902  0.858093
8               extra_trees  53.020429  72.036286  0.857677
9         gradient_boosting  53.676876  72.121650  0.857339
10           lightgbm_tuned  54.766373  72.193410  0.857055
11            xgboost_tuned  54.734186  73.511676  0.851787
12            random_forest  55.613818  74.643601  0.847187
13      random_forest_tuned  63.356502  78.912524  0.829209
14                 lightgbm  57.970616  79.134624  0.828246
15        extra_trees_tuned  66.926870  83.894603  0.806962

#### Observation on Metric-Based Comparison

The metric-based comparison shows that model performance is closely grouped among the strongest-performing models. Stacking Regression records the lowest MAE, while Lasso Regression records the lowest RMSE and highest R². Linear Regression and Ridge Regression also show very similar performance across the three metrics.

#### Important Point

The differences between the strongest-performing models are relatively small across the evaluation metrics. This indicates that model selection should consider the intended error measure and model characteristics rather than relying on a single performance metric alone.

#### 6.3 Visual Model Comparison

The model evaluation metrics were visualized to provide a direct comparison of predictive performance across all trained models.

Separate visualizations were created for MAE, RMSE, and R² so that differences in prediction error and explanatory performance can be examined independently.

In [7]:
# Visualizing MAE comparison

fig = px.bar(
    mae_comparison,
    x='Model',
    y='MAE',
    title='Model Comparison by MAE',
    labels={
        'Model': 'Model',
        'MAE': 'Mean Absolute Error'
    }
)

fig.update_xaxes(tickangle=45)

fig.show()

In [8]:
# Visualizing RMSE comparison

fig = px.bar(
    rmse_comparison,
    x='Model',
    y='RMSE',
    title='Model Comparison by RMSE',
    labels={
        'Model': 'Model',
        'RMSE': 'Root Mean Squared Error'
    }
)

fig.update_xaxes(tickangle=45)

fig.show()

In [9]:
# Visualizing R² comparison

fig = px.bar(
    r2_comparison,
    x='Model',
    y='R²',
    title='Model Comparison by R²',
    labels={
        'Model': 'Model',
        'R²': 'R² Score'
    }
)

fig.update_xaxes(tickangle=45)

fig.show()

#### Observation on Visual Model Comparison

The visual comparison confirms that the strongest-performing models are concentrated within a relatively narrow performance range. Lasso Regression, Linear Regression, Ridge Regression, and Stacking Regression show consistently strong results across the three evaluation metrics, while several tuned tree-based models show comparatively higher prediction errors.

#### Important Point

The visualizations reinforce that tuning does not automatically improve test-set performance. Several tuned tree-based models perform worse than their corresponding untuned versions on the held-out test dataset, demonstrating the importance of evaluating tuned models on unseen data.

#### 6.4 Untuned vs Tuned Model Comparison

Comparing the five tuned model pairs:

- Random Forest
- Extra Trees
- Gradient Boosting
- XGBoost
- LightGBM

The test-set performance of the untuned and tuned versions of the non-linear models was compared to assess whether hyperparameter optimization improved generalization performance.

RMSE was used as the primary comparison metric because it was also used as the scoring criterion during hyperparameter tuning.

In [10]:
# Defining the untuned and tuned model pairs

tuning_comparison = pd.DataFrame({
    'Model': [
        'Random Forest',
        'Extra Trees',
        'Gradient Boosting',
        'XGBoost',
        'LightGBM'
    ],
    'Untuned RMSE': [
        evaluation_results.loc[
            evaluation_results['Model'] == 'random_forest', 'RMSE'
        ].iloc[0],

        evaluation_results.loc[
            evaluation_results['Model'] == 'extra_trees', 'RMSE'
        ].iloc[0],

        evaluation_results.loc[
            evaluation_results['Model'] == 'gradient_boosting', 'RMSE'
        ].iloc[0],

        evaluation_results.loc[
            evaluation_results['Model'] == 'xgboost', 'RMSE'
        ].iloc[0],

        evaluation_results.loc[
            evaluation_results['Model'] == 'lightgbm', 'RMSE'
        ].iloc[0]
    ],
    'Tuned RMSE': [
        evaluation_results.loc[
            evaluation_results['Model'] == 'random_forest_tuned', 'RMSE'
        ].iloc[0],

        evaluation_results.loc[
            evaluation_results['Model'] == 'extra_trees_tuned', 'RMSE'
        ].iloc[0],

        evaluation_results.loc[
            evaluation_results['Model'] == 'gradient_boosting_tuned', 'RMSE'
        ].iloc[0],

        evaluation_results.loc[
            evaluation_results['Model'] == 'xgboost_tuned', 'RMSE'
        ].iloc[0],

        evaluation_results.loc[
            evaluation_results['Model'] == 'lightgbm_tuned', 'RMSE'
        ].iloc[0]
    ]
})

tuning_comparison

               Model  Untuned RMSE  Tuned RMSE
0      Random Forest     74.643601   78.912524
1        Extra Trees     72.036286   83.894603
2  Gradient Boosting     72.121650   69.921527
3            XGBoost     71.930902   73.511676
4           LightGBM     79.134624   72.193410

In [11]:
# Calculating the change in RMSE after tuning

tuning_comparison['RMSE Change (%)'] = (
    (
        tuning_comparison['Untuned RMSE']
        - tuning_comparison['Tuned RMSE']
    )
    / tuning_comparison['Untuned RMSE']
) * 100

tuning_comparison

               Model  Untuned RMSE  Tuned RMSE  RMSE Change (%)
0      Random Forest     74.643601   78.912524        -5.719074
1        Extra Trees     72.036286   83.894603       -16.461589
2  Gradient Boosting     72.121650   69.921527         3.050572
3            XGBoost     71.930902   73.511676        -2.197628
4           LightGBM     79.134624   72.193410         8.771399

#### Observation on Hyperparameter Tuning

Hyperparameter tuning produced mixed results across the five non-linear model families. Gradient Boosting and LightGBM achieved lower test-set RMSE after tuning, while Random Forest, Extra Trees, and XGBoost showed higher test-set RMSE than their untuned counterparts.

#### Important Point

The results demonstrate that hyperparameter optimization does not guarantee improved performance on unseen data. The effectiveness of tuning depends on the model, search space, and selected hyperparameters, making independent test-set evaluation essential.

#### 6.5 Ensemble Model Comparison

- Voting Regression
- Stacking Regression

The ensemble models were compared with their underlying individual models to examine whether combining multiple estimators improved predictive performance.

The analysis focuses on MAE, RMSE, and R² to determine how the Voting and Stacking approaches performed relative to the individual models used within the ensembles.

In [12]:
# Defining the individual and ensemble models for comparison

ensemble_models = [
    'ridge_regression',
    'gradient_boosting_tuned',
    'xgboost_tuned',
    'lightgbm_tuned',
    'voting_regression',
    'stacking_regression'
]

ensemble_comparison = evaluation_results[
    evaluation_results['Model'].isin(ensemble_models)
].copy()

ensemble_comparison = ensemble_comparison.sort_values(
    by='RMSE',
    ascending=True
).reset_index(drop=True)

ensemble_comparison

                     Model        MAE       RMSE        R²
0         ridge_regression  52.594296  67.589301  0.874706
1      stacking_regression  52.064850  67.782372  0.873989
2        voting_regression  52.910708  69.630254  0.867025
3  gradient_boosting_tuned  53.341282  69.921527  0.865910
4           lightgbm_tuned  54.766373  72.193410  0.857055
5            xgboost_tuned  54.734186  73.511676  0.851787

In [13]:
# Visualizing ensemble model performance

fig = px.bar(
    ensemble_comparison,
    x='Model',
    y='RMSE',
    title='Individual vs Ensemble Models — RMSE',
    labels={
        'Model': 'Model',
        'RMSE': 'Root Mean Squared Error'
    }
)

fig.update_xaxes(tickangle=45)

fig.show()

#### Observation on Ensemble Models

The ensemble models show different performance characteristics. Stacking Regression achieves a lower MAE than the individual models included in the ensemble, while its RMSE remains close to the strongest individual models. Voting Regression shows higher test-set RMSE than the strongest individual models in this comparison.

#### Important Point

The results indicate that combining multiple models does not automatically produce lower prediction error across all evaluation metrics. Ensemble methods can provide complementary prediction behavior, but their effectiveness depends on the performance and diversity of the underlying estimators.